name: Atualização Semanal de Notícias

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

# Adicionado para forçar o uso do Node.js 24 e remover os avisos de depreciação
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  atualizar_banco:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4 google-genai

      - name: Executar script de automação
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python automacao.py

      - name: Salvar (Commit) o novo noticias.json no repositório
        run: |
          git config --global user.name "Robô Folha de Coqueiros"
          git config --global user.email "automacao@folhadecoqueiros.com"
          git add noticias.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Atualização automática do banco de notícias" && git push)